<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.13.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EfCoreMastery.Application\EfCoreMastery.Application.csproj" />
    <ProjectReference Include="..\..\src\EfCoreMastery.Domain\EfCoreMastery.Domain.csproj" />
    <ProjectReference Include="..\..\src\EfCoreMastery.Infrastructure\EfCoreMastery.Infrastructure.csproj" />
  </ItemGroup>

</Project>
